CREATE DATABASE lqdty_t1;
CREATE DATABASE lqdty_t2;
CREATE DATABASE lqdty_t3;
CREATE DATABASE temporal;
CREATE DATABASE temporal_visibility;

GRANT ALL PRIVILEGES ON DATABASE catalog TO liquidity;
GRANT ALL PRIVILEGES ON DATABASE lqdty_t1 TO liquidity;
GRANT ALL PRIVILEGES ON DATABASE lqdty_t2 TO liquidity;
GRANT ALL PRIVILEGES ON DATABASE lqdty_t3 TO liquidity;
GRANT ALL PRIVILEGES ON DATABASE temporal TO liquidity;
GRANT ALL PRIVILEGES ON DATABASE temporal_visibility TO liquidity;
